//! Read-only structural inspection of the project-scoped guest Pi credential
//! files (`docs/adr/0011-pi-mixed-credential-ownership.md`, issue #93).
//!
//! Pi's user state is not checkout `.pi/`. Every shipped tool sees the same
//! project-scoped guest home mapping: guest `~/.pi` → `/agent-vm-state/pi` →
//! host `<project-state>/pi`. A guest can therefore leave a credential that any
//! later tool in this project can read, and a launch should say so before the
//! guest runs.
//!
//! This module is a *structural classifier*, not a resolver. Its defining
//! property is that it never resolves a credential: it does not run
//! `!command` values, expand environment references, refresh OAuth, import a
//! host credential, construct a proxy, or write/remove/rename anything. It
//! reads the two files with the descriptor-anchored, no-follow, bounded
//! [`GuestStateDir`] reader and returns a report containing only safe data:
//! a validated provider identifier, a closed credential-kind label, closed
//! field labels, and fixed reason labels. Raw JSON, credential bytes,
//! environment names, commands, model IDs and URLs never leave this module.
//!
//! Reporting is **not** ownership authorization. "Contains no secret bytes"
//! is weaker than "this exact provider entry was generated by agent-vm"; the
//! downstream reconciliation (#94) must consume a stronger per-provider
//! ownership predicate, not [`PiCredentialReport`]. See ADR-0011.
//!
//! The host Pi files `~/.pi/agent/{auth,models}.json` are separately protected
//! by ADR-0020 and are deliberately outside this module's scope.

use std::collections::BTreeSet;
use std::fmt;
use std::path::Path;

use serde::Deserialize;
use serde::de::{self, Deserializer, MapAccess, SeqAccess, Visitor};
use vstd::prelude::*;

use crate::host_paths::{EntryType, GuestStateDir};
use crate::protected_host_files::ProtectedFile;
use crate::secrets::is_known_placeholder;

verus! {

/// The longest provider identifier this module will echo back. A longer or
/// otherwise malformed identifier is rendered as `<unrecognized-provider>`
/// rather than escaped and printed.
pub(crate) const MAX_PROVIDER_ID_LEN: usize = 64;

/// How many findings a report retains before it collapses the rest into one
/// fixed truncation notice. Named so the launch notice can never grow without
/// bound on a hostile 8 MiB file.
pub(crate) const MAX_RETAINED_FINDINGS: usize = 128;

/// Bytes an accepted provider identifier may contain: ASCII lowercase
/// letters, digits, `-`, `_` and `.`. Anything else — uppercase, whitespace,
/// or a byte that could look like a secret — fails the whole-value check.
pub(crate) open spec fn provider_id_byte_allowed(byte: u8) -> bool {
    (b'a' <= byte && byte <= b'z')
        || (b'0' <= byte && byte <= b'9')
        || byte == b'-' || byte == b'_' || byte == b'.'
}

/// The whole provider-identifier decision: accepted iff the byte sequence is
/// non-empty, at most [`MAX_PROVIDER_ID_LEN`] bytes, and every byte is
/// allowed.
pub(crate) open spec fn provider_id_is_safe_spec(bytes: Seq<u8>) -> bool {
    1 <= bytes.len() && bytes.len() <= MAX_PROVIDER_ID_LEN
        && forall|i: int| 0 <= i < bytes.len() ==> provider_id_byte_allowed(bytes[i])
}

// The `<=` spelling (rather than clippy's suggested
// `(b'a'..=b'z').contains(&byte)`) is kept so the exec bytes stay
// syntactically the predicate the `verus!` spec fn unfolds to.
#[allow(clippy::manual_range_contains)]
fn provider_id_is_safe_bytes(bytes: &[u8]) -> (ok: bool)
    ensures ok == provider_id_is_safe_spec(bytes@),
{
    let len = bytes.len();
    if len == 0 || len > MAX_PROVIDER_ID_LEN {
        return false;
    }
    let mut i: usize = 0;
    while i < len
        invariant
            i <= len,
            len == bytes@.len(),
            1 <= len,
            len <= MAX_PROVIDER_ID_LEN,
            forall|j: int| 0 <= j < i ==> provider_id_byte_allowed(bytes@[j]),
        decreases len - i,
    {
        let byte = bytes[i];
        assert(provider_id_byte_allowed(byte) == (
            (b'a' <= byte && byte <= b'z')
                || (b'0' <= byte && byte <= b'9')
                || byte == b'-' || byte == b'_' || byte == b'.'
        ));
        // The predicate is inlined, not called: a `spec fn` erases under a
        // plain build, so an exec call to it would not compile.
        if !((b'a' <= byte && byte <= b'z')
            || (b'0' <= byte && byte <= b'9')
            || byte == b'-'
            || byte == b'_'
            || byte == b'.')
        {
            return false;
        }
        i += 1;
    }
    true
}

/// The finding-budget predicate: one more finding may be appended iff the
/// number already retained is strictly below [`MAX_RETAINED_FINDINGS`].
pub(crate) open spec fn finding_budget_allows(retained: usize) -> bool {
    retained < MAX_RETAINED_FINDINGS
}

fn finding_budget_allows_impl(retained: usize) -> (ok: bool)
    ensures ok == finding_budget_allows(retained),
{
    retained < MAX_RETAINED_FINDINGS
}

/// The most members any single JSON object may hold. Named so the *parse* of
/// a guest-controlled document is bounded: past this many members the whole
/// document is rejected as malformed before another member is read, so an
/// 8 MiB file cannot grow the retained member list (or the duplicate check)
/// without limit.
pub(crate) const MAX_OBJECT_MEMBERS: usize = 4096;

/// The per-object member-limit predicate: one more member may be parsed iff
/// the number already seen is strictly below [`MAX_OBJECT_MEMBERS`].
pub(crate) open spec fn object_member_budget_allows(retained: usize) -> bool {
    retained < MAX_OBJECT_MEMBERS
}

fn object_member_budget_allows_impl(retained: usize) -> (ok: bool)
    ensures ok == object_member_budget_allows(retained),
{
    retained < MAX_OBJECT_MEMBERS
}

} // verus!

/// Trusted adapter for [`provider_id_is_safe_bytes`]: the `&str` → bytes
/// measurement is outside the proof.
fn provider_id_is_safe(raw: &str) -> bool {
    provider_id_is_safe_bytes(raw.as_bytes())
}

/// Inspect the project-scoped guest Pi state under `state_dir`.
///
/// Never creates or mutates anything: a missing state root, missing file, or
/// missing legacy home is a normal absent result, and every other acquisition
/// failure becomes a fixed uninspectable finding rather than a launch error.
pub(crate) fn inspect_project(state_dir: &Path) -> PiCredentialReport {
    let mut sink = FindingSink::default();
    let mut files = Vec::new();
    match GuestStateDir::open_if_present(state_dir) {
        Ok(Some(guest)) => {
            inspect_location(&guest, Location::Canonical, &mut files, &mut sink);
            inspect_legacy(&guest, &mut files, &mut sink);
        }
        Ok(None) => {
            for file in PiFile::ALL {
                files.push(PiFileState {
                    location: Location::Canonical,
                    file,
                    status: PiFileStatus::Absent,
                });
            }
        }
        Err(_) => {
            for file in PiFile::ALL {
                files.push(PiFileState {
                    location: Location::Canonical,
                    file,
                    status: PiFileStatus::Uninspectable,
                });
                sink.push(uninspectable_finding(Location::Canonical, file));
            }
        }
    }
    sink.finish();
    PiCredentialReport {
        files,
        findings: sink.findings,
    }
}

/// The sanitized result of one structural scan. Holds no raw JSON, bytes,
/// paths or borrowed strings; every field is a closed enum or a validated
/// provider label.
#[derive(Debug, PartialEq, Eq)]
pub(crate) struct PiCredentialReport {
    files: Vec<PiFileState>,
    findings: Vec<Finding>,
}

impl PiCredentialReport {
    /// A report that inspected nothing (every file absent, no findings).
    /// Test-only: production always goes through [`inspect_project`], and this
    /// exists so `doctor`'s pure-rendering tests can build a report without
    /// reading the real filesystem.
    #[cfg(test)]
    pub(crate) fn uninspected() -> Self {
        Self {
            files: PiFile::ALL
                .iter()
                .map(|&file| PiFileState {
                    location: Location::Canonical,
                    file,
                    status: PiFileStatus::Absent,
                })
                .collect(),
            findings: Vec::new(),
        }
    }

    /// The stderr notice for a launch, or `None` when there is nothing to say
    /// (absent or clean files). A warning is advisory: it never denies the
    /// launch, and "no findings" is not a security guarantee.
    pub(crate) fn launch_warning(&self) -> Option<String> {
        if self.findings.is_empty() {
            return None;
        }
        let mut out = String::from(LAUNCH_WARNING_HEADER);
        for finding in &self.findings {
            out.push_str("\n    ");
            out.push_str(&finding_line(finding));
        }
        Some(out)
    }

    /// The `doctor` section. Shares [`finding_line`] with the launch notice so
    /// the two surfaces cannot disagree.
    pub(crate) fn doctor_section(&self) -> String {
        let mut out = String::from("==> guest-managed Pi credentials\n");
        out.push_str(
            "Structural inspection of guest-managed Pi state only; agent-vm never \
             resolves, imports, refreshes or removes it.\n",
        );
        for state in &self.files {
            let label = state.display_label();
            let lines = self.finding_lines_for(state);
            if lines.is_empty() {
                let status = match state.status {
                    PiFileStatus::Absent => "not present",
                    PiFileStatus::Inspected | PiFileStatus::Uninspectable => {
                        "no potentially sensitive entries found"
                    }
                };
                out.push_str(&format!("{label}: {status}\n"));
            } else {
                for line in lines {
                    out.push_str(&format!("{line}\n"));
                }
            }
        }
        out.push_str(
            "Only auth.json and models.json are inspected (settings, sessions and \
             installed packages are not).\n",
        );
        if self
            .files
            .iter()
            .any(|state| state.location == Location::Legacy)
        {
            out.push_str(
                "Legacy pre-#96 guest Pi state is present under the guest HOME and has \
                 not been moved; a launch migrates it only when the destination is free. \
                 doctor does not migrate anything.\n",
            );
        }
        out
    }

    fn finding_lines_for(&self, state: &PiFileState) -> Vec<String> {
        self.findings
            .iter()
            .filter(|finding| finding.file == state.file && finding.location == state.location)
            .map(finding_line)
            .collect()
    }
}

/// The shared, fixed-prose launch warning header. Findings themselves are
/// field-only.
const LAUNCH_WARNING_HEADER: &str = "==> WARNING: potentially sensitive guest-managed Pi credentials in this project's persistent state; any process in this guest can read them.";

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Location {
    Canonical,
    Legacy,
}

impl Location {
    fn source_prefix(self, file: PiFile) -> String {
        match self {
            Location::Canonical => file.label().to_string(),
            Location::Legacy => format!("legacy pre-#96 {}", file.label()),
        }
    }
}

/// The two state files this module knows about. Values are path-schema facts
/// only; the concrete paths are derived from [`ProtectedFile`] so the spelling
/// cannot drift from ADR-0020's protected-file table.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum PiFile {
    Auth,
    Models,
}

impl PiFile {
    const ALL: [PiFile; 2] = [Self::Auth, Self::Models];

    fn label(self) -> &'static str {
        match self {
            Self::Auth => "auth.json",
            Self::Models => "models.json",
        }
    }

    fn protected(self) -> ProtectedFile {
        match self {
            Self::Auth => ProtectedFile::PiAuth,
            Self::Models => ProtectedFile::PiModels,
        }
    }
}

/// How a scanned location's file turned out. `Inspected` may still carry
/// findings (a malformed document is inspected *and* potentially sensitive);
/// `Uninspectable` is reserved for acquisition failures that never reached a
/// parser.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum PiFileStatus {
    Absent,
    Inspected,
    Uninspectable,
}

#[derive(Debug, PartialEq, Eq)]
struct PiFileState {
    location: Location,
    file: PiFile,
    status: PiFileStatus,
}

impl PiFileState {
    fn display_label(&self) -> String {
        self.location.source_prefix(self.file)
    }
}

/// A closed credential-kind label. The custom `type` value itself never
/// crosses this interface.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum CredentialKind {
    ApiKey,
    OAuth,
    Configuration,
    Unknown,
}

impl CredentialKind {
    fn label(self) -> &'static str {
        match self {
            Self::ApiKey => "api_key",
            Self::OAuth => "oauth",
            Self::Configuration => "configuration",
            Self::Unknown => "unknown",
        }
    }
}

/// Why a finding exists. Kept as data so dedup/sort is deterministic; the
/// rendered line never echoes parser errors or raw input.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum FindingReason {
    GuestManaged,
    Unrecognized,
    Malformed,
    Uninspectable,
    Truncated,
}

/// A closed field label. Known schema names use enum labels; an unknown
/// header renders `headers.<custom>`, and any other unknown field renders
/// `<unrecognized-field>` so an attacker-controlled key is never echoed.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Field {
    Key,
    Access,
    Refresh,
    Expires,
    Env,
    ApiKey,
    BaseUrl,
    Token,
    Secret,
    Password,
    Authorization,
    HeadersAuthorization,
    HeadersCustom,
    Other,
}

impl Field {
    fn label(self) -> &'static str {
        match self {
            Self::Key => "key",
            Self::Access => "access",
            Self::Refresh => "refresh",
            Self::Expires => "expires",
            Self::Env => "env",
            Self::ApiKey => "apiKey",
            Self::BaseUrl => "baseUrl",
            Self::Token => "token",
            Self::Secret => "secret",
            Self::Password => "password",
            Self::Authorization => "authorization",
            Self::HeadersAuthorization => "headers.Authorization",
            Self::HeadersCustom => "headers.<custom>",
            Self::Other => "<unrecognized-field>",
        }
    }
}

/// A validated provider identifier, or the fixed placeholder that replaces an
/// arbitrary string. Never escapes and prints an arbitrary value.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum SafeProviderId {
    Unknown,
    Known(String),
}

impl SafeProviderId {
    fn new(raw: &str) -> Self {
        if provider_id_is_safe(raw) {
            Self::Known(raw.to_owned())
        } else {
            Self::Unknown
        }
    }

    fn render(&self) -> &str {
        match self {
            Self::Known(id) => id,
            Self::Unknown => "<unrecognized-provider>",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Finding {
    location: Location,
    file: PiFile,
    provider: SafeProviderId,
    kind: CredentialKind,
    fields: Vec<Field>,
    reason: FindingReason,
}

impl Finding {
    fn new(
        location: Location,
        file: PiFile,
        provider: SafeProviderId,
        kind: CredentialKind,
        fields: BTreeSet<Field>,
        reason: FindingReason,
    ) -> Self {
        Self {
            location,
            file,
            provider,
            kind,
            fields: fields.into_iter().collect(),
            reason,
        }
    }
}

fn uninspectable_finding(location: Location, file: PiFile) -> Finding {
    Finding::new(
        location,
        file,
        SafeProviderId::Unknown,
        CredentialKind::Unknown,
        BTreeSet::new(),
        FindingReason::Uninspectable,
    )
}

/// The one shared finding formatter. Both `doctor` and the launch notice call
/// this, so the two surfaces cannot drift.
fn finding_line(finding: &Finding) -> String {
    let source = finding.location.source_prefix(finding.file);
    match finding.reason {
        FindingReason::Uninspectable => {
            format!("{source}: potentially sensitive; structural inspection unavailable")
        }
        FindingReason::Truncated => {
            format!("{source}: additional potentially sensitive entries omitted")
        }
        FindingReason::GuestManaged | FindingReason::Unrecognized | FindingReason::Malformed => {
            // A file-wide structural finding (unparseable input, a non-object
            // root, duplicate members) has no provider and no field to name:
            // collapse it to one fixed potentially-sensitive line rather than
            // print an empty `<unrecognized-provider>` line.
            if finding.fields.is_empty() && finding.provider == SafeProviderId::Unknown {
                return format!(
                    "{source}: potentially sensitive; unrecognized or malformed structure"
                );
            }
            let fields = if finding.fields.is_empty() {
                "none".to_string()
            } else {
                finding
                    .fields
                    .iter()
                    .map(|field| field.label())
                    .collect::<Vec<_>>()
                    .join(",")
            };
            format!(
                "{source}: provider={} type={} fields={fields}",
                finding.provider.render(),
                finding.kind.label(),
            )
        }
    }
}

/// Bounded, deterministically-ordered finding collection.
#[derive(Default)]
struct FindingSink {
    findings: Vec<Finding>,
    truncated: bool,
}

impl FindingSink {
    fn push(&mut self, finding: Finding) {
        if finding_budget_allows_impl(self.findings.len()) {
            self.findings.push(finding);
        } else if !self.truncated {
            self.truncated = true;
            self.findings.push(Finding::new(
                finding.location,
                finding.file,
                SafeProviderId::Unknown,
                CredentialKind::Unknown,
                BTreeSet::new(),
                FindingReason::Truncated,
            ));
        }
    }

    fn finish(&mut self) {
        self.findings.sort();
        self.findings.dedup();
    }
}

// ---------------------------------------------------------------------------
// Acquisition

fn inspect_location(
    guest: &GuestStateDir,
    location: Location,
    files: &mut Vec<PiFileState>,
    sink: &mut FindingSink,
) {
    inspect_location_at(guest, location, Path::new("pi"), files, sink);
}

/// The legacy pre-#96 layout held a real `<state>/home/.pi` directory that the
/// compiled guest-HOME link now maps away. It is only scanned when that entry
/// is a **real directory**; the usual compiled mapping is a final symlink,
/// which must not be followed (following it would scan the same bytes twice
/// and would resolve a guest-planted redirect).
fn inspect_legacy(guest: &GuestStateDir, files: &mut Vec<PiFileState>, sink: &mut FindingSink) {
    match guest.entry_type(Path::new("home/.pi")) {
        Ok(Some(EntryType::Directory)) => {
            inspect_location_at(guest, Location::Legacy, Path::new("home/.pi"), files, sink);
        }
        Ok(Some(EntryType::Symlink)) | Ok(None) => {}
        Ok(Some(_)) | Err(_) => {
            for file in PiFile::ALL {
                files.push(PiFileState {
                    location: Location::Legacy,
                    file,
                    status: PiFileStatus::Uninspectable,
                });
                sink.push(uninspectable_finding(Location::Legacy, file));
            }
        }
    }
}

fn inspect_location_at(
    guest: &GuestStateDir,
    location: Location,
    root: &Path,
    files: &mut Vec<PiFileState>,
    sink: &mut FindingSink,
) {
    for file in PiFile::ALL {
        let relative = root.join(file.protected().pi_home_relative());
        match guest.read(&relative) {
            Ok(Some(bytes)) => {
                match file {
                    PiFile::Auth => inspect_auth(&bytes, location, sink),
                    PiFile::Models => inspect_models(&bytes, location, sink),
                }
                files.push(PiFileState {
                    location,
                    file,
                    status: PiFileStatus::Inspected,
                });
            }
            Ok(None) => files.push(PiFileState {
                location,
                file,
                status: PiFileStatus::Absent,
            }),
            Err(_) => {
                // Never log the discarded anyhow context: it can carry a path
                // and OS detail. Collapse to the fixed category.
                files.push(PiFileState {
                    location,
                    file,
                    status: PiFileStatus::Uninspectable,
                });
                sink.push(uninspectable_finding(location, file));
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Bounded JSON with duplicate-member rejection

/// A JSON value that preserves member order and rejects duplicate object keys,
/// which `serde_json::Value` silently collapses (`real key` then
/// `placeholder key` must not read as clean). Uses serde's default recursion
/// limit, and `serde_json::from_slice` consumes the whole document so trailing
/// junk fails.
enum Json {
    Null,
    Bool,
    Number(serde_json::Number),
    String(String),
    Array(Vec<Json>),
    Object(Vec<(String, Json)>),
}

impl Json {
    fn as_object(&self) -> Option<&[(String, Json)]> {
        match self {
            Json::Object(entries) => Some(entries),
            _ => None,
        }
    }

    fn as_str(&self) -> Option<&str> {
        match self {
            Json::String(value) => Some(value),
            _ => None,
        }
    }

    fn as_finite_number(&self) -> Option<f64> {
        match self {
            Json::Number(number) => number.as_f64().filter(|value| value.is_finite()),
            _ => None,
        }
    }
}

impl<'de> Deserialize<'de> for Json {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        struct JsonVisitor;

        impl<'de> Visitor<'de> for JsonVisitor {
            type Value = Json;

            fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str("a JSON value")
            }

            fn visit_bool<E>(self, _value: bool) -> Result<Json, E> {
                Ok(Json::Bool)
            }

            fn visit_i64<E>(self, value: i64) -> Result<Json, E> {
                Ok(Json::Number(value.into()))
            }

            fn visit_u64<E>(self, value: u64) -> Result<Json, E> {
                Ok(Json::Number(value.into()))
            }

            fn visit_f64<E>(self, value: f64) -> Result<Json, E>
            where
                E: de::Error,
            {
                serde_json::Number::from_f64(value)
                    .map(Json::Number)
                    .ok_or_else(|| E::custom("non-finite number"))
            }

            fn visit_str<E>(self, value: &str) -> Result<Json, E> {
                Ok(Json::String(value.to_owned()))
            }

            fn visit_string<E>(self, value: String) -> Result<Json, E> {
                Ok(Json::String(value))
            }

            fn visit_none<E>(self) -> Result<Json, E> {
                Ok(Json::Null)
            }

            fn visit_unit<E>(self) -> Result<Json, E> {
                Ok(Json::Null)
            }

            fn visit_some<D>(self, deserializer: D) -> Result<Json, D::Error>
            where
                D: Deserializer<'de>,
            {
                Json::deserialize(deserializer)
            }

            fn visit_seq<A>(self, mut seq: A) -> Result<Json, A::Error>
            where
                A: SeqAccess<'de>,
            {
                let mut items = Vec::new();
                while let Some(item) = seq.next_element()? {
                    items.push(item);
                }
                Ok(Json::Array(items))
            }

            fn visit_map<A>(self, mut map: A) -> Result<Json, A::Error>
            where
                A: MapAccess<'de>,
            {
                let mut entries: Vec<(String, Json)> = Vec::new();
                while let Some(key) = map.next_key::<String>()? {
                    // Bound the parse before reading another value: a
                    // guest-controlled 8 MiB document must not make the member
                    // list grow without bound. Past the cap the whole document
                    // is malformed (a fixed potentially-sensitive line).
                    if !object_member_budget_allows_impl(entries.len()) {
                        return Err(de::Error::custom("too many object members"));
                    }
                    let value = map.next_value::<Json>()?;
                    entries.push((key, value));
                }
                // Duplicate detection through a set, not a scan: this keeps
                // the check O(n log n) in the member count. The prior linear
                // scan inside the loop was O(n^2) and let a hostile ~1.4M
                // member file take ~40 minutes on the every-launch path (the
                // blocker in the #93 review).
                {
                    let mut seen: BTreeSet<&str> = BTreeSet::new();
                    for (key, _) in &entries {
                        if !seen.insert(key.as_str()) {
                            return Err(de::Error::custom("duplicate object member"));
                        }
                    }
                }
                Ok(Json::Object(entries))
            }
        }

        deserializer.deserialize_any(JsonVisitor)
    }
}

fn parse_document(bytes: &[u8]) -> Option<Json> {
    // `None` means "the whole document was not one well-formed JSON value".
    // The serde error itself is deliberately discarded: it can carry a
    // fragment of the raw guest input, which must never reach a report.
    //
    // Recursion depth is not a separate hole: `serde_json`'s default
    // 128-level limit rejects deeply nested input before this visitor
    // recurses, so the parse cannot blow the stack. The member bound in
    // `visit_map` is the resource limit this module adds itself.
    serde_json::from_slice::<Json>(bytes).ok()
}

fn member<'a>(members: &'a [(String, Json)], name: &str) -> Option<&'a Json> {
    members
        .iter()
        .find(|(key, _)| key == name)
        .map(|(_, value)| value)
}

fn string_is_placeholder(value: &Json) -> bool {
    matches!(value, Json::String(text) if is_known_placeholder(text))
}

fn is_bearer_placeholder(value: &str) -> bool {
    value
        .strip_prefix("Bearer ")
        .is_some_and(is_known_placeholder)
}

/// Field label for a credential-bearing member name, matched
/// case-insensitively for the conservative nested walk.
fn credential_field(name: &str) -> Option<Field> {
    let lower = name.to_ascii_lowercase();
    match lower.as_str() {
        "key" => Some(Field::Key),
        "apikey" => Some(Field::ApiKey),
        "access" | "accesstoken" => Some(Field::Access),
        "refresh" | "refreshtoken" => Some(Field::Refresh),
        "token" => Some(Field::Token),
        "secret" => Some(Field::Secret),
        "password" => Some(Field::Password),
        "authorization" => Some(Field::Authorization),
        _ => None,
    }
}

/// The state one models walk carries: the closed field labels it has seen and
/// whether it met an unrecognized shape or unknown member. Both travel
/// together through every level of the walk, so they are one value rather than
/// two `&mut` out-params at each call.
#[derive(Default)]
struct FieldAccumulator {
    fields: BTreeSet<Field>,
    unrecognized: bool,
}

impl FieldAccumulator {
    /// Record a credential-bearing field.
    fn flag(&mut self, field: Field) {
        self.fields.insert(field);
    }

    /// Record an unrecognized shape or unknown member: report the field *and*
    /// mark the whole entry unrecognized.
    fn flag_unrecognized(&mut self, field: Field) {
        self.fields.insert(field);
        self.unrecognized = true;
    }
}

/// Conservative credential-name walk for non-secret nested config containers
/// (`samplingParams`, `cost`, `compat`, arbitrary extension objects). Ordinary
/// parameter names and values stay quiet and are never printed; a
/// credential-looking member with a non-placeholder value warns.
fn walk_credential_names(value: &Json, acc: &mut FieldAccumulator) {
    match value {
        Json::Object(entries) => {
            for (name, child) in entries {
                if let Some(field) = credential_field(name) {
                    if !string_is_placeholder(child) {
                        acc.flag(field);
                    }
                } else if name.eq_ignore_ascii_case("headers") {
                    scan_headers(child, acc);
                } else {
                    walk_credential_names(child, acc);
                }
            }
        }
        Json::Array(items) => {
            for item in items {
                walk_credential_names(item, acc);
            }
        }
        _ => {}
    }
}

fn scan_headers(value: &Json, acc: &mut FieldAccumulator) {
    let Some(entries) = value.as_object() else {
        // A non-object header container has a shape Pi never writes, so it is
        // treated conservatively as unrecognized rather than as an empty map.
        acc.flag_unrecognized(Field::Other);
        return;
    };
    for (name, header) in entries {
        let field = if name.eq_ignore_ascii_case("authorization") {
            Field::HeadersAuthorization
        } else {
            Field::HeadersCustom
        };
        match header {
            Json::String(text) if is_known_placeholder(text) || is_bearer_placeholder(text) => {}
            _ => {
                acc.flag(field);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// auth.json

fn inspect_auth(bytes: &[u8], location: Location, sink: &mut FindingSink) {
    let json = match parse_document(bytes) {
        Some(json) => json,
        None => {
            sink.push(Finding::new(
                location,
                PiFile::Auth,
                SafeProviderId::Unknown,
                CredentialKind::Unknown,
                BTreeSet::new(),
                FindingReason::Malformed,
            ));
            return;
        }
    };
    let Some(entries) = json.as_object() else {
        sink.push(Finding::new(
            location,
            PiFile::Auth,
            SafeProviderId::Unknown,
            CredentialKind::Unknown,
            BTreeSet::new(),
            FindingReason::Malformed,
        ));
        return;
    };
    for (name, entry) in entries {
        if let Some(found) = classify_auth_entry(location, name, entry) {
            sink.push(found);
        }
    }
}

fn classify_auth_entry(location: Location, name: &str, entry: &Json) -> Option<Finding> {
    let provider = SafeProviderId::new(name);
    let Some(members) = entry.as_object() else {
        return Some(Finding::new(
            location,
            PiFile::Auth,
            provider,
            CredentialKind::Unknown,
            BTreeSet::new(),
            FindingReason::Malformed,
        ));
    };
    let type_value = member(members, "type").and_then(Json::as_str);
    let kind = match type_value {
        Some("api_key") => CredentialKind::ApiKey,
        Some("oauth") => CredentialKind::OAuth,
        _ => CredentialKind::Unknown,
    };
    // An absent or unrecognized `type` is itself an unrecognized entry: there
    // is no way to know which fields are credential-bearing and which are
    // merely extra.
    let mut unrecognized = !matches!(type_value, Some("api_key") | Some("oauth"));
    let mut malformed = false;
    let mut fields: BTreeSet<Field> = BTreeSet::new();

    for (key, value) in members {
        match key.as_str() {
            "type" => {}
            "key" if kind == CredentialKind::ApiKey => match value {
                // The pinned Pi accepts an absent or empty key with no
                // credential bytes; an exact known placeholder is also quiet.
                Json::String(text) if text.is_empty() || is_known_placeholder(text) => {}
                _ => {
                    fields.insert(Field::Key);
                }
            },
            // `env` is an object of string-valued references in the pinned
            // schema. Any nonempty map (or a value of the wrong shape) is
            // potentially sensitive; its names and values are never reported.
            "env" if kind == CredentialKind::ApiKey => match value {
                Json::Object(entries) if entries.is_empty() => {}
                _ => {
                    fields.insert(Field::Env);
                }
            },
            "access" if kind == CredentialKind::OAuth => {
                if !string_is_placeholder(value) {
                    fields.insert(Field::Access);
                }
            }
            "refresh" if kind == CredentialKind::OAuth => {
                if !string_is_placeholder(value) {
                    fields.insert(Field::Refresh);
                }
            }
            "expires" if kind == CredentialKind::OAuth => {
                if value.as_finite_number().is_none() {
                    fields.insert(Field::Expires);
                    malformed = true;
                }
            }
            other => match credential_field(other) {
                Some(field) => {
                    if !string_is_placeholder(value) {
                        fields.insert(field);
                    }
                }
                None => {
                    // Extra members on a credential entry are never ignored:
                    // #91 plans an `accountId` producer, and a future landed
                    // producer must extend this rule and its tests together.
                    unrecognized = true;
                    fields.insert(Field::Other);
                }
            },
        }
    }

    // Required OAuth shape: string access, string refresh, finite expires.
    if kind == CredentialKind::OAuth {
        for (required, field) in [
            ("access", Field::Access),
            ("refresh", Field::Refresh),
            ("expires", Field::Expires),
        ] {
            if member(members, required).is_none() {
                fields.insert(field);
                malformed = true;
            }
        }
    }

    if fields.is_empty() && !unrecognized && !malformed {
        return None;
    }
    let reason = if malformed {
        FindingReason::Malformed
    } else if unrecognized {
        FindingReason::Unrecognized
    } else {
        FindingReason::GuestManaged
    };
    Some(Finding::new(
        location,
        PiFile::Auth,
        provider,
        kind,
        fields,
        reason,
    ))
}

// ---------------------------------------------------------------------------
// models.json

fn inspect_models(bytes: &[u8], location: Location, sink: &mut FindingSink) {
    let json = match parse_document(bytes) {
        Some(json) => json,
        None => {
            sink.push(configuration_finding(
                location,
                SafeProviderId::Unknown,
                BTreeSet::new(),
                FindingReason::Malformed,
            ));
            return;
        }
    };
    let Some(root) = json.as_object() else {
        sink.push(configuration_finding(
            location,
            SafeProviderId::Unknown,
            BTreeSet::new(),
            FindingReason::Malformed,
        ));
        return;
    };
    // `{}` is the one explicit no-content exception: there is nothing to
    // expose. It is *not* a claim that the document passes Pi's schema
    // validation — a nonempty document still needs a `providers` object and
    // recognized top-level members.
    if root.is_empty() {
        return;
    }
    for (name, _) in root {
        if name != "providers" {
            let mut fields = BTreeSet::new();
            fields.insert(Field::Other);
            sink.push(configuration_finding(
                location,
                SafeProviderId::Unknown,
                fields,
                FindingReason::Unrecognized,
            ));
        }
    }
    match member(root, "providers") {
        Some(Json::Object(providers)) => {
            for (name, provider) in providers {
                inspect_provider(location, SafeProviderId::new(name), provider, sink);
            }
        }
        Some(_) => {
            let mut fields = BTreeSet::new();
            fields.insert(Field::Other);
            sink.push(configuration_finding(
                location,
                SafeProviderId::Unknown,
                fields,
                FindingReason::Malformed,
            ));
        }
        None => {
            let mut fields = BTreeSet::new();
            fields.insert(Field::Other);
            sink.push(configuration_finding(
                location,
                SafeProviderId::Unknown,
                fields,
                FindingReason::Unrecognized,
            ));
        }
    }
}

fn inspect_provider(
    location: Location,
    provider: SafeProviderId,
    value: &Json,
    sink: &mut FindingSink,
) {
    let Some(members) = value.as_object() else {
        sink.push(configuration_finding(
            location,
            provider,
            BTreeSet::new(),
            FindingReason::Unrecognized,
        ));
        return;
    };
    let mut acc = FieldAccumulator::default();
    for (key, child) in members {
        match key.as_str() {
            // Ordinary, non-credential provider fields from the pinned schema.
            "name" | "api" | "authHeader" => {}
            "baseUrl" => {
                if base_url_warns(child) {
                    acc.flag(Field::BaseUrl);
                }
            }
            "apiKey" => {
                if !string_is_placeholder(child) {
                    acc.flag(Field::ApiKey);
                }
            }
            // `oauth` here is a selector, not a stored token; the only quiet
            // value is the exact literal `radius`.
            "oauth" => {
                if child.as_str() != Some("radius") {
                    acc.flag_unrecognized(Field::Other);
                }
            }
            "headers" => scan_headers(child, &mut acc),
            "models" => inspect_models_array(child, &mut acc),
            "modelOverrides" => inspect_model_overrides(child, &mut acc),
            "compat" => walk_credential_names(child, &mut acc),
            _ => acc.flag_unrecognized(Field::Other),
        }
    }
    push_if_findings(location, provider, acc, sink);
}

fn inspect_models_array(value: &Json, acc: &mut FieldAccumulator) {
    let Some(items) = as_array(value) else {
        acc.flag_unrecognized(Field::Other);
        return;
    };
    for item in items {
        inspect_model_object(item, true, acc);
    }
}

fn inspect_model_overrides(value: &Json, acc: &mut FieldAccumulator) {
    let Some(entries) = value.as_object() else {
        acc.flag_unrecognized(Field::Other);
        return;
    };
    for (_, item) in entries {
        inspect_model_object(item, false, acc);
    }
}

fn inspect_model_object(value: &Json, is_model: bool, acc: &mut FieldAccumulator) {
    let Some(members) = value.as_object() else {
        acc.flag_unrecognized(Field::Other);
        return;
    };
    for (key, child) in members {
        let ordinary = if is_model {
            matches!(
                key.as_str(),
                "id" | "name" | "api" | "reasoning" | "input" | "contextWindow" | "maxTokens"
            )
        } else {
            matches!(
                key.as_str(),
                "name" | "reasoning" | "input" | "contextWindow" | "maxTokens"
            )
        };
        if ordinary {
            continue;
        }
        match key.as_str() {
            "headers" => scan_headers(child, acc),
            "samplingParams" => walk_credential_names(child, acc),
            "baseUrl" => {
                if is_model {
                    if base_url_warns(child) {
                        acc.flag(Field::BaseUrl);
                    }
                } else {
                    acc.flag_unrecognized(Field::Other);
                }
            }
            "compat" | "cost" | "promptCache" | "thinkingLevelMap" => {
                walk_credential_names(child, acc)
            }
            _ => acc.flag_unrecognized(Field::Other),
        }
    }
}

fn as_array(value: &Json) -> Option<&[Json]> {
    match value {
        Json::Array(items) => Some(items),
        _ => None,
    }
}

/// A `baseUrl` can embed credentials in its userinfo or query, and a
/// non-endpoint value cannot be trusted to be one. Reported as a bare field
/// label; no URL text or network access.
fn base_url_warns(value: &Json) -> bool {
    let Some(text) = value.as_str() else {
        return true;
    };
    match url::Url::parse(text) {
        Ok(url) => {
            !matches!(url.scheme(), "http" | "https")
                || !url.username().is_empty()
                || url.password().is_some()
                || url.query().is_some()
                || url.fragment().is_some()
        }
        Err(_) => true,
    }
}

fn push_if_findings(
    location: Location,
    provider: SafeProviderId,
    acc: FieldAccumulator,
    sink: &mut FindingSink,
) {
    if acc.fields.is_empty() {
        return;
    }
    let reason = if acc.unrecognized {
        FindingReason::Unrecognized
    } else {
        FindingReason::GuestManaged
    };
    sink.push(configuration_finding(
        location, provider, acc.fields, reason,
    ));
}

fn configuration_finding(
    location: Location,
    provider: SafeProviderId,
    fields: BTreeSet<Field>,
    reason: FindingReason,
) -> Finding {
    Finding::new(
        location,
        PiFile::Models,
        provider,
        CredentialKind::Configuration,
        fields,
        reason,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn auth_findings(body: &str) -> Vec<Finding> {
        let mut sink = FindingSink::default();
        inspect_auth(body.as_bytes(), Location::Canonical, &mut sink);
        sink.finish();
        sink.findings
    }

    fn models_findings(body: &str) -> Vec<Finding> {
        let mut sink = FindingSink::default();
        inspect_models(body.as_bytes(), Location::Canonical, &mut sink);
        sink.finish();
        sink.findings
    }

    fn line_of(finding: &Finding) -> String {
        finding_line(finding)
    }

    fn assert_quiet(findings: &[Finding]) {
        assert!(findings.is_empty(), "expected quiet, got {findings:#?}");
    }

    // -- auth.json ---------------------------------------------------------

    #[test]
    fn empty_auth_object_is_quiet() {
        assert_quiet(&auth_findings("{}"));
    }

    #[test]
    fn missing_and_empty_and_placeholder_api_key_are_quiet() {
        for body in [
            r#"{"anthropic":{"type":"api_key"}}"#,
            r#"{"anthropic":{"type":"api_key","key":""}}"#,
            r#"{"anthropic":{"type":"api_key","key":"<P1>"}}"#,
            r#"{"anthropic":{"type":"api_key","key":"<P1>","env":{}}}"#,
        ] {
            let body = body.replace("<P1>", crate::secrets::ANTHROPIC_ACCESS_PLACEHOLDER);
            assert_quiet(&auth_findings(&body));
        }
    }

    #[test]
    fn one_byte_mutation_of_a_placeholder_warns_with_field_and_kind() {
        let mutated = format!("{}x", crate::secrets::ANTHROPIC_ACCESS_PLACEHOLDER);
        let findings = auth_findings(&format!(
            r#"{{"anthropic":{{"type":"api_key","key":"{mutated}"}}}}"#
        ));
        assert_eq!(findings.len(), 1);
        assert_eq!(
            line_of(&findings[0]),
            "auth.json: provider=anthropic type=api_key fields=key"
        );
    }

    #[test]
    fn nonempty_env_or_unknown_member_warns() {
        let body = format!(
            r#"{{"anthropic":{{"type":"api_key","key":"{}","env":{{"NAME":"ref"}}}}}}"#,
            crate::secrets::ANTHROPIC_ACCESS_PLACEHOLDER,
        );
        let env = auth_findings(&body);
        assert!(line_of(&env[0]).contains("fields=env"));

        let extra = auth_findings(r#"{"anthropic":{"type":"api_key","key":null}}"#);
        assert!(line_of(&extra[0]).contains("fields=key"));
    }

    #[test]
    fn oauth_placeholder_pair_is_quiet_and_real_refresh_warns() {
        let quiet = format!(
            r#"{{"anthropic":{{"type":"oauth","access":"{}","refresh":"{}","expires":1}}}}"#,
            crate::secrets::ANTHROPIC_ACCESS_PLACEHOLDER,
            crate::secrets::ANTHROPIC_REFRESH_PLACEHOLDER,
        );
        assert_quiet(&auth_findings(&quiet));

        let real_refresh = format!(
            r#"{{"anthropic":{{"type":"oauth","access":"{}","refresh":"real-token","expires":1}}}}"#,
            crate::secrets::ANTHROPIC_ACCESS_PLACEHOLDER,
        );
        assert_eq!(
            line_of(&auth_findings(&real_refresh)[0]),
            "auth.json: provider=anthropic type=oauth fields=refresh"
        );
    }

    #[test]
    fn unknown_type_and_extra_members_warn() {
        let unknown = auth_findings(r#"{"anthropic":{"type":"weird","key":"real"}}"#);
        assert_eq!(unknown.len(), 1);
        assert!(line_of(&unknown[0]).contains("type=unknown"));
        assert!(line_of(&unknown[0]).contains("fields=key"));

        let account_id = format!(
            r#"{{"anthropic":{{"type":"oauth","access":"{}","refresh":"{}","expires":1,"accountId":"0"}}}}"#,
            crate::secrets::ANTHROPIC_ACCESS_PLACEHOLDER,
            crate::secrets::ANTHROPIC_REFRESH_PLACEHOLDER,
        );
        assert_eq!(
            line_of(&auth_findings(&account_id)[0]),
            "auth.json: provider=anthropic type=oauth fields=<unrecognized-field>"
        );
    }

    #[test]
    fn nonzero_exit_fields_in_a_credential_entry_are_never_ignored() {
        // A known access placeholder must not hide a real refresh token.
        let body = format!(
            r#"{{"anthropic":{{"type":"oauth","access":"{}","refresh":"real","expires":1}}}}"#,
            crate::secrets::ANTHROPIC_ACCESS_PLACEHOLDER,
        );
        assert_eq!(
            line_of(&auth_findings(&body)[0]),
            "auth.json: provider=anthropic type=oauth fields=refresh"
        );
    }

    #[test]
    fn malformed_and_duplicate_and_non_object_auth_warn_without_raw_input() {
        for body in [
            "not json",
            r#"{"anthropic":42}"#,
            r#"[1,2,3]"#,
            r#"{"anthropic":{"type":"api_key"},"anthropic":{"type":"api_key"}}"#,
            r#"{"anthropic":{"type":"api_key","key":"","key":"real"}}"#,
            r#"{"anthropic":{"type":"api_key"}}trailing"#,
        ] {
            let findings = auth_findings(body);
            assert!(!findings.is_empty(), "expected a finding for {body}");
            let rendered = line_of(&findings[0]);
            assert!(!rendered.contains("real"), "raw value leaked: {rendered}");
            assert!(
                !rendered.contains("not json"),
                "raw input leaked: {rendered}"
            );
        }
    }

    #[test]
    fn file_wide_parse_failure_renders_one_fixed_line() {
        assert_eq!(
            line_of(&auth_findings("not json")[0]),
            "auth.json: potentially sensitive; unrecognized or malformed structure"
        );
        assert_eq!(
            line_of(&models_findings("[]")[0]),
            "models.json: potentially sensitive; unrecognized or malformed structure"
        );
        // A scalar *entry* still names its valid provider, with no field.
        assert_eq!(
            line_of(&auth_findings(r#"{"anthropic":42}"#)[0]),
            "auth.json: provider=anthropic type=unknown fields=none"
        );
    }

    #[test]
    fn invalid_utf8_file_is_malformed() {
        let mut sink = FindingSink::default();
        inspect_auth(&[0x7b, 0xff, 0x7d], Location::Canonical, &mut sink);
        sink.finish();
        assert_eq!(sink.findings.len(), 1);
        assert_eq!(sink.findings[0].reason, FindingReason::Malformed);
    }

    #[test]
    fn unsafe_provider_identifier_is_replaced_not_echoed() {
        let findings = auth_findings(r#"{"UPPER CASE":{"type":"api_key","key":"real"}}"#);
        assert_eq!(
            line_of(&findings[0]),
            "auth.json: provider=<unrecognized-provider> type=api_key fields=key"
        );
    }

    // -- models.json -------------------------------------------------------

    #[test]
    fn empty_models_and_models_without_credentials_are_quiet() {
        assert_quiet(&models_findings("{}"));
        assert_quiet(&models_findings(
            r#"{"providers":{"demo":{"name":"Demo","baseUrl":"https://example.test/v1","api":"openai","authHeader":true,"models":[{"id":"m","name":"M","reasoning":true,"contextWindow":1000,"maxTokens":10}]}}}"#,
        ));
    }

    #[test]
    fn all_optional_ordinary_fields_and_radius_selector_are_quiet() {
        let body = r#"{"providers":{"demo":{
                "name":"Demo","baseUrl":"https://example.test/v1","apiKey":"<P>",
                "api":"openai","oauth":"radius","authHeader":false,
                "headers":{"Authorization":"Bearer <P>"},
                "compat":{"supportsTemperature":true},
                "models":[{
                    "id":"m","name":"M","api":"openai","baseUrl":"https://example.test/m",
                    "reasoning":true,"thinkingLevelMap":{},"input":["text"],
                    "cost":{"input":1,"output":2},"promptCache":{},
                    "contextWindow":1000,"maxTokens":10,
                    "samplingParams":{"temperature":0.2},"headers":{},
                    "compat":{"supportsTemperature":true}
                }],
                "modelOverrides":{"m":{"name":"M","reasoning":false,"samplingParams":{"topP":0.9}}}
            }}}"#
            .replace("<P>", crate::secrets::ANTHROPIC_ACCESS_PLACEHOLDER);
        assert_quiet(&models_findings(&body));
    }

    #[test]
    fn a_credential_only_in_model_overrides_is_still_reported() {
        // Removing the modelOverrides traversal must fail this test: the only
        // credential-bearing position in the document is inside the override.
        let body = r#"{"providers":{"demo":{"modelOverrides":{"m":{"headers":{"X-K":"real"}}}}}}"#;
        assert_eq!(
            line_of(&models_findings(body)[0]),
            "models.json: provider=demo type=configuration fields=headers.<custom>"
        );
        let override_key = r#"{"providers":{"demo":{"modelOverrides":{"m":{"samplingParams":{"apiKey":"real"}}}}}}"#;
        assert_eq!(
            line_of(&models_findings(override_key)[0]),
            "models.json: provider=demo type=configuration fields=apiKey"
        );
    }

    #[test]
    fn provider_model_and_override_headers_warn_field_only() {
        let body = r#"{"providers":{"demo":{"apiKey":"real","headers":{"X-Api-Key":"secret"},"models":[{"id":"m","headers":{"authorization":"real"}}],"modelOverrides":{"m":{"headers":{"X-Custom":"real"}}}}}}"#;
        let findings = models_findings(body);
        assert_eq!(findings.len(), 1);
        let line = line_of(&findings[0]);
        assert!(line.contains("provider=demo"));
        assert!(line.contains("headers.<custom>"));
        assert!(line.contains("headers.Authorization"));
        assert!(!line.contains("secret"));
    }

    #[test]
    fn credential_like_sampling_param_warns_but_ordinary_param_is_quiet() {
        let body =
            r#"{"providers":{"demo":{"models":[{"id":"m","samplingParams":{"apiKey":"real"}}]}}}"#;
        let findings = models_findings(body);
        assert_eq!(
            line_of(&findings[0]),
            "models.json: provider=demo type=configuration fields=apiKey"
        );
    }

    #[test]
    fn unknown_provider_field_and_unknown_top_level_member_warn() {
        let body = r#"{"providers":{"demo":{"mystery":"x"}},"extra":1}"#;
        let findings = models_findings(body);
        assert!(
            findings
                .iter()
                .any(|f| line_of(f).contains("fields=<unrecognized-field>"))
        );
    }

    #[test]
    fn malformed_models_is_fixed_warning_without_raw_input() {
        for body in ["nope", r#"[1]"#, r#"{"providers":[]}"#] {
            let findings = models_findings(body);
            assert!(!findings.is_empty(), "expected a finding for {body}");
            let rendered = line_of(&findings[0]);
            assert!(!rendered.contains("nope"));
            assert!(!rendered.contains("providers"));
        }
    }

    #[test]
    fn a_bad_auth_file_still_allows_models_findings() {
        let mut sink = FindingSink::default();
        inspect_auth(b"not json", Location::Canonical, &mut sink);
        inspect_models(
            br#"{"providers":{"demo":{"apiKey":"real"}}}"#,
            Location::Canonical,
            &mut sink,
        );
        sink.finish();
        assert!(sink.findings.iter().any(|f| f.file == PiFile::Models));
    }

    // -- bounds and determinism -------------------------------------------

    #[test]
    fn findings_are_bounded_and_ordered() {
        let mut body = String::from("{");
        for index in 0..(MAX_RETAINED_FINDINGS + 50) {
            if index > 0 {
                body.push(',');
            }
            body.push_str(&format!(r#""p{index}":{{"type":"api_key","key":"real"}}"#));
        }
        body.push('}');
        let findings = auth_findings(&body);
        assert_eq!(findings.len(), MAX_RETAINED_FINDINGS + 1);
        assert!(
            findings
                .iter()
                .any(|finding| finding.reason == FindingReason::Truncated)
        );
    }

    #[test]
    fn an_object_past_the_member_limit_is_rejected_as_malformed() {
        // S-1 regression. A hostile member count must be rejected by the parse
        // bound, so the duplicate check and the retained member list stay
        // bounded on the every-launch path. This test fails if
        // `MAX_OBJECT_MEMBERS` is removed: the over-limit object would then be
        // fully parsed and produce many truncated findings instead of one
        // malformed one.
        let mut oversized = String::from("{");
        for index in 0..=MAX_OBJECT_MEMBERS {
            if index > 0 {
                oversized.push(',');
            }
            oversized.push_str(&format!(r#""p{index}":{{"type":"api_key","key":"real"}}"#));
        }
        oversized.push('}');
        let findings = auth_findings(&oversized);
        assert_eq!(
            findings.len(),
            1,
            "an over-limit object is one file-wide malformed finding"
        );
        assert_eq!(findings[0].reason, FindingReason::Malformed);

        // An object exactly at the limit is still scanned, not rejected.
        let mut at_limit = String::from("{");
        for index in 0..MAX_OBJECT_MEMBERS {
            if index > 0 {
                at_limit.push(',');
            }
            at_limit.push_str(&format!(r#""p{index}":{{"type":"api_key","key":"real"}}"#));
        }
        at_limit.push('}');
        let findings = auth_findings(&at_limit);
        assert!(
            findings.len() > 1,
            "an object at the member limit must still be scanned"
        );
        assert!(
            findings
                .iter()
                .all(|finding| finding.reason != FindingReason::Malformed),
            "the at-limit object must not be rejected as malformed"
        );
    }

    #[test]
    fn deeply_nested_input_is_rejected_without_a_stack_overflow() {
        // The member bound does not have to double as a depth bound:
        // `serde_json`'s default 128-level recursion limit rejects this before
        // the visitor recurses, so the result is the fixed malformed line.
        let depth = 200;
        let nested = format!("{}{}", "[".repeat(depth), "]".repeat(depth));
        let body = format!(r#"{{"p":{{"type":"api_key","key":{nested}}}}}"#);
        let findings = auth_findings(&body);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].reason, FindingReason::Malformed);
    }

    #[test]
    fn duplicate_findings_are_deduplicated() {
        // The same provider appearing twice is already rejected as a duplicate
        // key; a duplicate *finding* would come from the same entry being
        // classified twice, which must collapse.
        let mut sink = FindingSink::default();
        let entry = r#"{"type":"api_key","key":"real"}"#;
        inspect_auth(
            format!(r#"{{"demo":{entry},"other":{entry}}}"#).as_bytes(),
            Location::Canonical,
            &mut sink,
        );
        sink.finish();
        assert_eq!(sink.findings.len(), 2);
    }

    #[test]
    fn provider_id_safety_matches_grammar_boundaries() {
        assert!(provider_id_is_safe("anthropic"));
        assert!(provider_id_is_safe("a-b_c.d9"));
        assert!(!provider_id_is_safe(""));
        assert!(!provider_id_is_safe("Upper"));
        assert!(!provider_id_is_safe(&"a".repeat(MAX_PROVIDER_ID_LEN + 1)));
        assert!(provider_id_is_safe(&"a".repeat(MAX_PROVIDER_ID_LEN)));
    }

    #[test]
    fn exact_placeholder_equality_is_whole_value() {
        assert!(is_known_placeholder("msb-anthropic-placeholder-a-v2"));
        assert!(!is_known_placeholder("msb-anthropic-placeholder-a-v2x"));
        assert!(!is_known_placeholder("xmsb-anthropic-placeholder-a-v2"));
        assert!(!is_known_placeholder(""));
    }

    // -- real filesystem: acquisition and non-mutation (V2) ---------------

    fn write_at(root: &Path, relative: &str, body: &str) {
        let path = root.join(relative);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, body).unwrap();
    }

    #[test]
    fn a_missing_state_root_is_absent_and_creates_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("does-not-exist");
        let report = inspect_project(&root);
        assert!(report.launch_warning().is_none());
        assert!(!root.exists(), "inspection created the state root");
        assert!(
            report.doctor_section().contains("auth.json: not present"),
            "{}",
            report.doctor_section()
        );
    }

    #[test]
    fn dangling_symlink_is_uninspectable_and_the_other_file_still_reports() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("pi/agent")).unwrap();
        std::os::unix::fs::symlink(
            root.join("pi/agent/missing"),
            root.join("pi/agent/auth.json"),
        )
        .unwrap();
        write_at(
            root,
            "pi/agent/models.json",
            r#"{"providers":{"demo":{"apiKey":"real"}}}"#,
        );
        let report = inspect_project(root);
        let warning = report.launch_warning().expect("must warn");
        assert!(
            warning.contains("auth.json: potentially sensitive; structural inspection unavailable"),
            "{warning}"
        );
        assert!(
            warning.contains("models.json: provider=demo type=configuration fields=apiKey"),
            "{warning}"
        );
    }

    #[test]
    fn legacy_real_directory_is_scanned_and_a_final_symlink_is_not_followed() {
        // A real pre-#96 directory: reported as legacy.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write_at(
            root,
            "home/.pi/agent/auth.json",
            r#"{"anthropic":{"type":"api_key","key":"real"}}"#,
        );
        let report = inspect_project(root);
        let warning = report.launch_warning().expect("must warn");
        assert!(
            warning
                .contains("legacy pre-#96 auth.json: provider=anthropic type=api_key fields=key"),
            "{warning}"
        );

        // The compiled guest-HOME mapping is a final symlink: never followed.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let target = root.join("elsewhere");
        write_at(
            &target,
            "agent/auth.json",
            r#"{"anthropic":{"type":"api_key","key":"real"}}"#,
        );
        std::fs::create_dir_all(root.join("home")).unwrap();
        std::os::unix::fs::symlink(&target, root.join("home/.pi")).unwrap();
        let report = inspect_project(root);
        assert!(
            report.launch_warning().is_none(),
            "a final symlink must not be followed: {:?}",
            report.launch_warning()
        );
    }

    #[test]
    fn canonical_and_legacy_locations_are_both_reported() {
        // A real pre-#96 `home/.pi` directory can coexist with the canonical
        // `pi/` tree (migration then refuses to merge them), so neither
        // location may hide the other: the report must name both.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write_at(
            root,
            "pi/agent/auth.json",
            r#"{"canonicalprov":{"type":"api_key","key":"real"}}"#,
        );
        write_at(
            root,
            "home/.pi/agent/models.json",
            r#"{"providers":{"legacyprov":{"apiKey":"real"}}}"#,
        );
        let report = inspect_project(root);
        let warning = report.launch_warning().expect("must warn");
        assert!(
            warning.contains("auth.json: provider=canonicalprov type=api_key fields=key"),
            "{warning}"
        );
        assert!(
            warning.contains(
                "legacy pre-#96 models.json: provider=legacyprov type=configuration fields=apiKey"
            ),
            "{warning}"
        );
        let doctor = report.doctor_section();
        assert!(
            doctor.contains("auth.json: provider=canonicalprov type=api_key fields=key"),
            "{doctor}"
        );
        assert!(
            doctor.contains(
                "legacy pre-#96 models.json: provider=legacyprov type=configuration fields=apiKey"
            ),
            "{doctor}"
        );
        assert!(doctor.contains("has not been moved"), "{doctor}");
    }

    #[test]
    fn an_unsafe_legacy_node_is_uninspectable_not_clean() {
        // Only a **real directory** at `home/.pi` is legacy state. Any other
        // final node (here a regular file) must fail closed as uninspectable,
        // never as absent/clean.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("home")).unwrap();
        std::fs::write(root.join("home/.pi"), b"not a directory").unwrap();
        let report = inspect_project(root);
        let warning = report.launch_warning().expect("must warn");
        assert!(
            warning.contains(
                "legacy pre-#96 auth.json: potentially sensitive; structural inspection unavailable"
            ),
            "{warning}"
        );
        assert!(
            warning.contains(
                "legacy pre-#96 models.json: potentially sensitive; structural inspection unavailable"
            ),
            "{warning}"
        );

        // An unsafe *ancestor* (a symlinked `home`) is the shape a guest can
        // plant; the no-follow check must fail closed for the legacy location
        // too, not silently skip it.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("realhome/.pi/agent")).unwrap();
        std::os::unix::fs::symlink(root.join("realhome"), root.join("home")).unwrap();
        let report = inspect_project(root);
        let warning = report.launch_warning().expect("must warn");
        assert!(
            warning.contains(
                "legacy pre-#96 auth.json: potentially sensitive; structural inspection unavailable"
            ),
            "{warning}"
        );
    }

    #[test]
    fn an_oversized_file_is_uninspectable_not_clean() {
        // The spec names "oversized" explicitly. A file past the read bound is
        // rejected by the reader before the scanner sees any bytes, so it must
        // render the fixed uninspectable finding rather than a clean report.
        // A sparse file pins the size check without writing 8 MiB of bytes.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let path = root.join("pi/agent/auth.json");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let file = std::fs::File::create(&path).unwrap();
        file.set_len(crate::host_paths::MAX_GUEST_STATE_FILE_BYTES + 1)
            .unwrap();
        drop(file);
        let report = inspect_project(root);
        let warning = report.launch_warning().expect("oversized must warn");
        assert!(
            warning.contains("auth.json: potentially sensitive; structural inspection unavailable"),
            "{warning}"
        );
        assert!(
            report.doctor_section().contains("models.json: not present"),
            "{}",
            report.doctor_section()
        );
    }

    #[test]
    fn two_scans_do_not_mutate_bytes_identity_or_timestamps() {
        use std::os::unix::fs::MetadataExt;
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write_at(
            root,
            "pi/agent/auth.json",
            r#"{"anthropic":{"type":"api_key","key":"real"}}"#,
        );
        write_at(
            root,
            "pi/agent/models.json",
            r#"{"providers":{"demo":{"apiKey":"real"}}}"#,
        );
        let snapshot = || {
            let path = root.join("pi/agent/auth.json");
            let meta = std::fs::symlink_metadata(&path).unwrap();
            (
                std::fs::read(&path).unwrap(),
                meta.ino(),
                meta.dev(),
                meta.size(),
                meta.mode(),
                meta.nlink(),
                (meta.mtime(), meta.mtime_nsec()),
                (meta.ctime(), meta.ctime_nsec()),
            )
        };
        let before = snapshot();
        let _ = inspect_project(root);
        let _ = inspect_project(root);
        assert_eq!(
            before,
            snapshot(),
            "two scans must preserve bytes and metadata (atime excluded, per the #93 amendment)"
        );
    }

    // -- property tests (V1) ----------------------------------------------

    proptest! {
        /// Changing one non-placeholder credential value for another leaves the
        /// *rendered* report identical: the second value's bytes never reach it.
        #[test]
        fn swapping_a_non_placeholder_value_leaves_the_report_unchanged(
            a in "[A-Za-z0-9]{1,24}",
            b in "[A-Za-z0-9]{1,24}",
        ) {
            prop_assume!(a != b);
            prop_assume!(!is_known_placeholder(&a) && !is_known_placeholder(&b));
            let first = auth_findings(&format!(r#"{{"p":{{"type":"api_key","key":"{a}"}}}}"#));
            let second = auth_findings(&format!(r#"{{"p":{{"type":"api_key","key":"{b}"}}}}"#));
            prop_assert_eq!(first, second);
        }

        /// Any byte mutation of a placeholder is not the placeholder.
        #[test]
        fn mutating_a_placeholder_is_not_a_placeholder(suffix in "[A-Za-z0-9]{1,8}") {
            for placeholder in crate::secrets::ALL_PLACEHOLDERS {
                let appended = format!("{}{}", placeholder, suffix);
                let prepended = format!("{}{}", suffix, placeholder);
                prop_assert!(!is_known_placeholder(&appended));
                prop_assert!(!is_known_placeholder(&prepended));
            }
        }

        /// A provider id outside the accepted grammar never reaches output:
        /// every one collapses to the fixed `<unrecognized-provider>` label.
        #[test]
        fn unsafe_provider_ids_never_reach_output(raw in ".{1,80}") {
            prop_assume!(!provider_id_is_safe(&raw));
            let quoted = serde_json::to_string(&raw).unwrap();
            let findings = auth_findings(&format!(
                r#"{{{quoted}:{{"type":"api_key","key":"real"}}}}"#
            ));
            prop_assert_eq!(findings.len(), 1);
            prop_assert_eq!(
                finding_line(&findings[0]),
                "auth.json: provider=<unrecognized-provider> type=api_key fields=key"
            );
        }

        /// A custom header name is never echoed — only `headers.<custom>`.
        #[test]
        fn custom_header_names_never_reach_output(name in ".{1,40}") {
            prop_assume!(!name.eq_ignore_ascii_case("authorization"));
            let quoted = serde_json::to_string(&name).unwrap();
            let body = format!(
                r#"{{"providers":{{"demo":{{"headers":{{{quoted}:"secret-value"}}}}}}}}"#
            );
            let findings = models_findings(&body);
            prop_assert_eq!(
                findings.iter().map(finding_line).collect::<Vec<_>>(),
                vec![
                    "models.json: provider=demo type=configuration fields=headers.<custom>"
                        .to_string()
                ]
            );
        }
    }
}
