#!/usr/bin/env python3
"""SPIKE (throwaway) -- emit composed build files from the tool catalog.

Question this answers: can a *single generated Dockerfile* (or a bake DAG over
the existing per-tool Dockerfiles) replace the chained per-tool OCI layers,
while keeping tool bumps from cascading through every layer above them?

It reuses the real `images/tools/*/Dockerfile` bodies, so the generated linear
image is a faithful equivalent of today's 7-step chain. The multi-stage variant
is the interesting one: independent per-tool stages + one merge stage, so
bumping one tool rebuilds that stage and the merge only.

This file is disposable. See README.md for what to look at.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TOOLS_DIR = REPO / "images" / "tools"
DEFAULT_ORDER = ["dsh", "pi", "codex", "opencode", "claude", "copilot"]
BASE_PATH = "/usr/local/bin:/usr/bin:/usr/sbin:/bin"

# Where each tool's build leaves files. The merge model must know this; the
# chained-diff model gets it for free from the layer diff. Deriving these
# automatically (by diffing a stage against the base, or by switching each tool
# to its own prefix) is the real work a production version would need.
COPY_ROOTS = {
    "dsh": ["/opt/agent-vm/dsh", "/usr/local/bin"],
    "pi": [
        "/opt/agent-vm/pi",
        "/opt/agent-vm/pi-packages",
        "/opt/agent-vm/pi-extensions",
        "/opt/agent-vm/seed.d",
        "/usr/local/bin",
    ],
    # codex installs a private prefix at /opt/agent/.codex and symlinks its bin
    # into /opt/agent/.local/bin. (The first cut of this table guessed
    # /opt/agent/.local only, which silently shipped an image with no codex.)
    "codex": ["/opt/agent/.codex", "/opt/agent/.local"],
    "opencode": ["/opt/agent/.opencode", "/usr/local/bin"],
    "claude": [
        "/opt/agent/.local",
        "/opt/agent/.claude",
        "/opt/agent-vm/claude-seed",
        "/opt/agent-vm/seed.d",
    ],
    # copilot's npm prefix on this base is /usr, so it lands in
    # /usr/lib/node_modules with a /usr/bin/copilot symlink -- NOT /usr/local.
    "copilot": ["/usr/lib/node_modules", "/usr/bin/copilot"],
}

HEADER = (
    "# GENERATED by spikes/generated-dockerfile/generate.py -- DO NOT EDIT.\n"
    "# Throwaway spike artifact, not part of the build.\n"
)


def strip_header(tool: str) -> list[str]:
    """Return the tool Dockerfile body (everything after its `FROM`)."""
    lines = (TOOLS_DIR / tool / "Dockerfile").read_text().splitlines()
    for i, line in enumerate(lines):
        if line.strip().startswith("FROM "):
            return rewrite_context_paths(tool, lines[i + 1 :])
    raise SystemExit(f"no FROM in {tool}/Dockerfile")


def rewrite_context_paths(tool: str, body: list[str]) -> list[str]:
    """The single generated build context is the repo root, so every relative
    COPY source / bind-mount source must be repointed at images/tools/<tool>/."""
    prefix = f"images/tools/{tool}/"
    out: list[str] = []
    for line in body:
        s = line
        if "--mount" in s:
            s = re.sub(
                r"source=([A-Za-z0-9_][A-Za-z0-9_./-]*)",
                lambda m: m.group(0)
                if m.group(1).startswith("/")
                else f"source={prefix}{m.group(1)}",
                s,
            )
        stripped = s.strip()
        if stripped.startswith("COPY ") and "--from=" not in stripped:
            tokens = stripped.split()
            flags = [t for t in tokens[1:] if t.startswith("--")]
            rest = [t for t in tokens[1:] if not t.startswith("--")]
            dest, srcs = rest[-1], rest[:-1]
            srcs = [x if x.startswith("/") else prefix + x for x in srcs]
            s = "COPY " + " ".join(flags + srcs + [dest])
        out.append(s)
    return out


def path_prefixes(body: list[str]) -> list[str]:
    prefs: list[str] = []
    for line in body:
        m = re.match(r"\s*ENV PATH=(.+)$", line)
        if not m:
            continue
        head = m.group(1).split("${PATH}")[0].rstrip(":")
        for p in head.split(":"):
            if p and p not in prefs:
                prefs.append(p)
    return prefs


def fixture_body(tool: str, prefix: bool = False) -> list[str]:
    """A tiny synthetic tool body for the fast measurement run.

    `prefix=True` demonstrates the disjoint-prefix discipline: the tool writes
    only under /opt/tool-<name>, so its merge footprint is definitional rather
    than a hand-maintained path list.
    """
    root = f"/opt/tool-{tool}" if prefix else f"/opt/agent/.{tool}"
    return [
        f"ARG AGENT_VERSION_{tool.upper()}=",
        f"RUN mkdir -p {root}/bin \\",
        f" && echo \"{tool} ${{AGENT_VERSION_{tool.upper()}}}\" > {root}/version \\",
        f" && printf '#!/bin/sh\\necho {tool}\\n' > {root}/bin/{tool} \\",
        f" && chmod -R a+rX {root}",
        f"ENV PATH={root}/bin:${{PATH}}",
        f"RUN echo FIXTURE_TOOL={tool} version=${{AGENT_VERSION_{tool.upper()}:-unset}}",
    ]


def emit_linear(tools: list[str], base: str, bodies: dict[str, list[str]], out: Path) -> None:
    parts = [HEADER.rstrip(), f"ARG BASE_IMAGE={base}", "FROM ${BASE_IMAGE}"]
    for t in tools:
        parts.append(f"# ----- tool layer: {t} -----")
        parts.extend(bodies[t])
    out.write_text("\n".join(parts) + "\n")


def dedup(values: list[str]) -> list[str]:
    out: list[str] = []
    for v in values:
        if v not in out:
            out.append(v)
    return out


def emit_multistage(
    tools: list[str],
    base: str,
    bodies: dict[str, list[str]],
    roots: dict[str, list[str]],
    prefixes: dict[str, list[str]],
    out: Path,
    link: bool = False,
) -> None:
    parts = [HEADER.rstrip(), f"ARG BASE_IMAGE={base}"]
    for t in tools:
        parts.append(f"# ----- independent tool stage: {t} -----")
        parts.append(f"FROM ${{BASE_IMAGE}} AS tool_{t}")
        parts.extend(bodies[t])
    parts.append("# ----- merge: union the per-tool footprints -----")
    parts.append("FROM ${BASE_IMAGE} AS merged")
    for t in tools:
        for root in roots[t]:
            parts.append(f"COPY{' --link' if link else ''} --from=tool_{t} {root} {root}")
    flat = dedup([p for t in tools for p in prefixes[t]])
    parts.append(f"ENV PATH={':'.join(flat + [BASE_PATH])}")
    out.write_text("\n".join(parts) + "\n")


def emit_bake(tools: list[str], base: str, merge_dockerfile: str, out: Path) -> None:
    lines = [
        "// GENERATED by spikes/generated-dockerfile/generate.py -- DO NOT EDIT.",
        'variable "BASE_IMAGE" { default = "' + base + '" }',
        "",
    ]
    for t in tools:
        lines += [
            f'target "tool-{t}" {{',
            f'  context = "images/tools/{t}"',
            '  dockerfile = "Dockerfile"',
            f'  args = {{ BASE_IMAGE = "${{BASE_IMAGE}}" }}',
            f'  tags = ["agent-vm-{t}:spike"]',
            "}",
            "",
        ]
    ctx = {f"tool_{t}": f"target:tool-{t}" for t in tools}
    lines += [
        'target "merge" {',
        '  context = "."',
        f'  dockerfile = "{merge_dockerfile}"',
        '  args = { BASE_IMAGE = "${BASE_IMAGE}" }',
        "  contexts = {",
    ]
    for k, v in ctx.items():
        lines.append(f'    {k} = "{v}"')
    lines += ["  }", '  tags = ["agent-vm-template:spike"]', "}", ""]
    out.write_text("\n".join(lines))


def emit_merge_from_contexts(
    tools: list[str],
    base: str,
    roots: dict[str, list[str]],
    prefixes: dict[str, list[str]],
    out: Path,
    link: bool = False,
) -> None:
    parts = [HEADER.rstrip(), f"ARG BASE_IMAGE={base}", "FROM ${BASE_IMAGE}"]
    parts.append("# Tool bodies come from the real images/tools/*/Dockerfile targets")
    parts.append("# referenced as bake named contexts, not regenerated here.")
    for t in tools:
        for root in roots[t]:
            parts.append(f"COPY{' --link' if link else ''} --from=tool_{t} {root} {root}")
    flat = dedup([p for t in tools for p in prefixes[t]])
    parts.append(f"ENV PATH={':'.join(flat + [BASE_PATH])}")
    out.write_text("\n".join(parts) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tools", default=",".join(DEFAULT_ORDER))
    ap.add_argument("--base-image", default="ghcr.io/wirenboard/agent-vm-base:latest")
    ap.add_argument("--fixture", action="store_true", help="synthetic fast tools, debian base")
    ap.add_argument("--prefix", action="store_true", help="disjoint per-tool prefix (fixture only)")
    ap.add_argument("--link", action="store_true", help="COPY --link in the merge stage")
    ap.add_argument("--out", default=str(Path(__file__).parent / "out"))
    args = ap.parse_args()

    tools = [t.strip() for t in args.tools.split(",") if t.strip()]
    unknown = [t for t in tools if t not in DEFAULT_ORDER]
    if unknown:
        raise SystemExit(f"unknown tools: {unknown}")

    base = "debian:13-slim" if args.fixture else args.base_image
    bodies = {
        t: (fixture_body(t, args.prefix) if args.fixture else strip_header(t))
        for t in tools
    }
    if args.fixture:
        root = (lambda t: f"/opt/tool-{t}") if args.prefix else (lambda t: f"/opt/agent/.{t}")
        roots = {t: [root(t)] for t in tools}
    else:
        roots = {t: COPY_ROOTS[t] for t in tools}
    prefixes = {t: path_prefixes(bodies[t]) for t in tools}

    out = Path(args.out)
    if not out.is_absolute():
        out = (Path.cwd() / out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    emit_linear(tools, base, bodies, out / "linear.Dockerfile")
    emit_multistage(tools, base, bodies, roots, prefixes, out / "multistage.Dockerfile", args.link)
    emit_merge_from_contexts(tools, base, roots, prefixes, out / "merge.Dockerfile", args.link)
    try:
        rel_merge = str((out / "merge.Dockerfile").relative_to(REPO))
    except ValueError:
        rel_merge = str(out / "merge.Dockerfile")
    emit_bake(tools, base, rel_merge, out / "docker-bake.hcl")
    print(f"wrote {out}/linear.Dockerfile")
    print(f"wrote {out}/multistage.Dockerfile")
    print(f"wrote {out}/merge.Dockerfile")
    print(f"wrote {out}/docker-bake.hcl")


if __name__ == "__main__":
    main()
